### ISSUE TITLE
There is no main.py in /src

### ISSUE THREAD

**Issue by albertyou2** [marianafza/ImageClustering#1]
Hi @marianafza 
Great work and it's very helpful for me !

But when I run this command :
python main.py -p ../images -k SIFT -n 200 -s FALSE -d SIFT -g  SAMPLEP -c KMEANS -m euclidean -t 100 -f  FMAXMIN -h SBIN -a KMEANS -r 2

I got an error: 
python: can't open file 'main.py': [Errno 2] No such file or directory

And  I has checked the 'src' folder,there was no main.py file 

Another question is : Could you please give a suggestion about how to set these arguments(or give a default value for each argument for comnon case)?
The arguments are too much and  i don't know how the argument will effect the cluster results .

thank you very much!

**Comment by marianaAfonso** [comment]
Hi Albert. 

Thanks for your question and for being interested in my work. In this repository, I might have forgotten to change the name of the main script to main.py. Could you please try this other repository, which is also mine and is the one referenced on my paper (it contains the main.py): 

Repository: https://github.com/marianaAfonso/BOFClustering.
Paper: http://www.bmva.org/bmvc/2015/papers/paper146/paper146.pdf

In relation to the parameters, the goal is to be able to vary the algorithms used for each stage to determine how the influence the final results. If you want more information on the best methods after my evaluation, please check my paper.

Thanks! 
Mariana

**Comment by albertyou2** [comment]
HI @marianaAfonso
OK! I will checkout that Repository and read your paper!.
Thank you again!
